services:
  postgres:
    restart: unless-stopped
    image: "postgres:9.6"
    healthcheck:
      interval: "30s"
      timeout: "60s"
      retries: "5"
      start_period: 10s

      # Using default user "postgres" from sentry/sentry.conf.example.py or value of POSTGRES_USER if provided
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_replication_slots=1",
        "-c",
        "max_wal_senders=1",
      ]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    entrypoint: /opt/sentry/postgres-entrypoint.sh
    volumes:
      - "sentry-postgres:/var/lib/postgresql/data"
      - type: bind
        read_only: true
        source: ./postgres/
        target: /opt/sentry/
    # pikalov
    network_mode: host

volumes:
  # These store application data that should persist across restarts.
  sentry-postgres:
    external: true
